### ISSUE TITLE
read method does not work ( MicroPython in M5Stack )

### ISSUE THREAD

**Issue by XM03** [AmbientDataInc/ambient-python-lib#3]
as is: 
M5burnerよりUI Flow(v1.6.5-en, MicroPython-1.11)をM5Stackに書き込み。
VSコードから下記コードを実行。（一部省略）
```python
from m5stack import *
from m5ui import *
from uiflow import *
import ambient

while True:
    am = ambient.Ambient(---, '---', '---', '---')
    d = am.read(n=10)
    wait_ms(20000)
``` 
以下エラーが表示される。
```
unexpected keyword argument 'timeout'
```
エラー箇所はambient.py内にて
```
self.r = self.requests.get(url, timeout = timeout)
```
import urequestsをself.requestsとしているので、
urequest.py内の、getメソッド内の、requestメソッドに引数timeoutが存在しない事が問題ではないかと思い
（urequestとrequest、MicroPythonとPythonの違い？？）
試行錯誤をしてみたのですが、
力不足で根本的にはエラーが解消できずご助力いただければ幸いです。

to be: 
エラーが起きずにAmbientよりデータが取れる。

environment: 
UI Flow(v1.6.5-en, MicroPython-1.11)
M5Stack
Mac OSX
VSコード(vscode-m5stack-mpy)

to reproduce:
M5Stack上でプログラムを実行。

frequency: 
必ず。

link:
urequests.py
https://github.com/micropython/micropython-lib/blob/master/urequests/urequests.py

初めてのissue投稿で、不足や失礼などございましたら申し訳ございません。
何卒よろしくお願いいたします。

**Comment by TakehikoShimojima** [comment]
MicroPythonのrequestsモジュールであるurequestsではtimeoutがサポートされていませんでした。
MicroPythonではtimeoutを使わないように修正します。
