### ISSUE TITLE
AttributeError: 'Ambient' object has no attribute 'debug'

### ISSUE THREAD

**Issue by changosan** [AmbientDataInc/ambient-python-lib#4]
昨日、新しいラズパイにAmbientをインストールしてデータを送信したらタイトルのエラーが発生。
送信方法は下記で、Python3.7.3を使用しています。
```
am = ambient.Ambient(channel_id, write_key)
am.send(data)
```
現状正常に送信できているラズパイと比較したところ、ambientのversionが**0.1.7**に変わっています。
ambient.pyをversion**0.1.7**から手持ちのversion**0.1.6**に置き換えたら正常に送信できた。
version**0.1.7**の ```if self.debug:``` の前に ```self.debug = False``` を挿入したら正常に送信できているようです。
初めての投稿なので失礼な点があるかもしれませんが、よろしくお願いします。

**Comment by TakehikoShimojima** [comment]
ご指摘、ありがとうございます。修正しました。
